<?php

$GS_SECURED_LAYERS = array(
	"AFREEMAN.GEOSERVER_TEST_PT_HTTPS",
	"AFREEMAN.GEOSERVER_TEST_POLY_HTTPS",
	"AFREEMAN.GEOSERVER_TEST_LINE_HTTPS",
	"GISDATA.RECORDED_LAND_PLANS_POLY",
	"EOHED.TOWN_PRI_POLY_160",
	"EOHED.SRPEDD_LOCAL_PDA_PPA_POLY_201",
	"DCR.ROADS_TRAILS_LINE_TEST",
	"DAR.FIELDS_PONDS_ORG1000"
);


?>
